# Generated by Django 4.2.11 on 2024-04-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_restaurante_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
