# Generated by Django 4.2.11 on 2024-04-08 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('restaurante', '0004_alter_restaurante_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurante',
            options={'ordering': ('-time_creation',)},
        ),
        migrations.AddField(
            model_name='restaurante',
            name='time_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categorias.categoria'),
        ),
    ]
